GetOpeningWeekendData <- function(df) {
  # Extract only the first game for each season from the data in the tidy 
  # format generated by GetSeasonalResultData function.
  #
  # Args:
  #  df: dataframe containing tidy information generated by 
  #      GetSeasonalResultData function
  #
  # Returns:
  #  dataframe containing only the information about the opening games for
  #  each season
  openingGames <- df %>%
    group_by(Season, Team) %>%
    mutate(FinalPoints = max(Points), 
           FinalGoalsFor = sum(FTGF), 
           FinalGoalsAgainst = sum(FTGA),
           Game = rank(Date)) %>%
    ungroup() %>%
    group_by(Season, Game) %>%
    mutate(TablePosition = n() + 1 - min_rank(FinalPoints)) %>%
    ungroup() %>%
    filter(Game == 1) %>%
    group_by(Team) %>%
    mutate(FinalPointsLast = lag(FinalPoints),
           FinalGoalsForLast = lag(FinalGoalsFor),
           FinalGoalsAgainstLast = lag(FinalGoalsAgainst),
           FinalTablePositionLast = lag(TablePosition)) %>%
    ungroup()
  
  return(openingGames)
}

GetOpeningWeekendHomeAdvantage <- function(openingGames) {
  # Function that gets the information whether or not playing game at the
  # home venue gives teams any advantage or not for the opening games of
  # the season.
  #
  # Args:
  #  openingGames: dataframe containing opening games information generated by
  #                GetOpeningWeekend function
  #
  # Returns:
  #  table containing percentage of win, loss and drawn games for home side
  #  for opening games
  openingGamesHomeAdvantage <- openingGames %>%
    group_by(Venue) %>%
    summarise(PercentageWin = round((sum(Outcome == "W")/n()) * 100, 2), 
              PercentageLoss = round((sum(Outcome == "L")/n()) * 100, 2),
              PercentageDraw = round((sum(Outcome == "D")/n()) * 100, 2))
  
  return(openingGamesHomeAdvantage)
}

GetSeasonalHomeAdvantage <- function(df) {
  # Function that gets the information whether or not playing game at the
  # home venue gives teams any advantage or not for the games through the
  # whole season.
  #
  # Args:
  #  df: dataframe containing tidy information generated by 
  #      GetSeasonalResultData function
  #
  # Returns:
  #  table containing percentage of win, loss and drawn games for home side
  #  for the whole season
  homeAdvantage <- df %>%
    group_by(Venue) %>%
    summarise(PercentageWin = round((sum(Outcome == "W")/n()) * 100, 2), 
              PercentageLoss = round((sum(Outcome == "L")/n()) * 100, 2),
              PercentageDraw = round((sum(Outcome == "D")/n()) * 100, 2))
  
  return(homeAdvantage)
}

PlotWinPercentageSeasonal <- function(openingGames) {
  # Plot the win percentage for home teams on opening weekend by season.
  #
  # Args:
  #  openingGames: dataframe containing opening games information generated by
  #                GetOpeningWeekend functionn
  openingGames %>%
    group_by(Season, Venue) %>%
    summarise(PercentageWin = round((sum(Outcome == "W")/n()) * 100, 2), 
              PercentageLoss = round((sum(Outcome == "L")/n()) * 100, 2),
              PercentageDraw = round((sum(Outcome == "D")/n()) * 100, 2)) %>%
    gather(key = "Result", value = "Percentage", PercentageWin:PercentageDraw) %>%
    mutate(Result = case_when(Result == "PercentageWin" ~ "Winning Percentage",
                              Result == "PercentageLoss" ~ "Losing Percentage",
                              TRUE ~ "Percent Draws")) %>%
    filter(Venue == "Home") %>%
    ggplot(aes(Season, Percentage, color = Result)) +
    geom_point() +
    geom_line(size = 1) +
    theme_tq() +
    scale_color_tq() +
    theme(axis.text.x = element_text(angle = 90, 
                                     vjust = 0.5, 
                                     hjust = 1, 
                                     size = 12),
          axis.text.y = element_text(size = 12),
          legend.title = element_blank()) +
    labs(x = "Year",
         y = "Percentage of Results by Year",
         title = "The Percent of Results (Win, Draw, Loss) per Season\nfor Home Teams on Opening Weekend")
}

GetHomeAdvantagePerTeam <- function(openingGames) {
  # Get win percentage for opening games played on home venue for each team
  # through seasons.
  #
  # Args:
  #  openingGames: dataframe containing opening games information generated by
  #                GetOpeningWeekend functionn
  #
  # Returns:
  #  table containing percentage of win, as well as number of games played on
  #  home ground for each team.
  homeAdvantagePerTeam <- openingGames %>%
    group_by(Team) %>%
    mutate(NumberOfSeasons = n()) %>%
    ungroup() %>%
    filter(NumberOfSeasons >= max(NumberOfSeasons)/2) %>% 
    group_by(Team) %>%
    select(-NumberOfSeasons) %>%
    ungroup() %>%
    group_by(Team, Venue) %>%
    summarise(WinningPercentage = round((sum(Outcome == "W")/n()) * 100, 2), 
              TotalNumberOfGames = n()) %>%
    ungroup()
  
  return(homeAdvantagePerTeam)
}

GetWinPercentageHomeAndAway <- function(teamAdvantage) {
  # Plot bar chart displaying information about winning percentage for
  # each teams home and away games on the opening weekend through seasons.
  #
  # Args:
  #  teamAdvantage: dataframe containing opening games home advantage 
  #                 information generated by the GetHomeAdvTeam function
  teamAdvantage %>%
    arrange(-WinningPercentage) %>%
    mutate(Team = factor(Team, unique(Team)),
           Venue = factor(Venue, levels = c("Home", "Away"))) %>%
    ggplot(aes(Team, WinningPercentage, fill = Venue)) +
    facet_wrap(~Venue, scales = "fixed", ncol = 1) +
    geom_bar(stat = "identity") +
    theme_tq() +
    scale_fill_tq() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 12),
          axis.text.y = element_text(size = 12),
          strip.text = element_text(size = 12),
          legend.position = "none") +
    geom_text(aes(x = Team, y = WinningPercentage + 5, label = paste0("n=", as.character(TotalNumberOfGames)))) +
    labs(x = "",
         y = "Winning Percentage",
         title = "Winning Percentage for Teams on Opening Weekend both Home and Away",
         subtitle = "Only Teams Participating in more than Half of the Seasons were included")
}

GetOverallWinPercentage <- function(openingGames) {
  # Calculate overall win percentage in the opening games for each team and
  # display information using bar chart.
  #
  # Args:
  #  openingGames: dataframe containing opening games information generated by
  #                GetOpeningWeekend functionn
  openingGames %>%
    group_by(Team) %>%
    mutate(NumberOfSeasons = n()) %>%
    ungroup() %>%
    filter(NumberOfSeasons >= max(NumberOfSeasons)/2) %>% 
    group_by(Team) %>%
    select(-NumberOfSeasons) %>%
    ungroup() %>%
    group_by(Team) %>%
    summarise(WinningPercentage = round((sum(Outcome == "W")/n()) * 100, 2), 
              TotalNumberOfGames = n()) %>%
    ungroup() %>%
    arrange(-WinningPercentage) %>%
    mutate(Team = factor(Team, unique(Team))) %>%
    ggplot(aes(Team, WinningPercentage)) +
    geom_bar(stat = "identity", fill = "red", color = "black") +
    theme_tq() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 12),
          axis.text.y = element_text(size = 12),
          strip.text = element_text(size = 12),
          legend.position = "none") +
    geom_text(aes(x = Team, y = WinningPercentage + 5, label = paste0("n=", as.character(TotalNumberOfGames)))) +
    labs(x = "",
         y = "Winning Percentage",
         title = "Winning Percentage for Teams on Opening Weekend",
         subtitle = "Only Teams Participating in more than Half of the Seasons were included")
}
